[versions]
# Plugins
agp = "8.13.2"
kotlin = "2.3.10"
spotless = "8.2.1"
detekt = "1.23.8"

# Android SDK
androidMinSdk = "26"
androidCompileSdk = "36"
androidTargetSdk = "36"

# Google
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
material = "1.13.0"

# Google - Compose
activityCompose = "1.12.3"
composeBom = "2026.01.00"

# Other
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.10.0"

[libraries]
# Google
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
material = { module = "com.google.android.material:material", version.ref = "material" }

# Google - Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

# Other
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
